
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class AccountsReceivable
{

    public decimal AccountsReceivableID { get; set; }

    public decimal ProspectID { get; set; }

    public decimal AgeRangeID { get; set; }

    public decimal Dollars { get; set; }

    public decimal CompanyID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
