
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class AdditionalProduct
{

    public decimal ID { get; set; }

    public string ProductName { get; set; }

    public string Description { get; set; }

    public string CostPerUnit { get; set; }

    public bool Active { get; set; }

    public Nullable<decimal> DivisionID { get; set; }

    public Nullable<decimal> ProductID { get; set; }

    public decimal CompanyID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
