
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class CompetitorPlant
{

    public decimal CompetitorPlantID { get; set; }

    public decimal CompetitorID { get; set; }

    public string PlantName { get; set; }

    public System.DateTime Inserted { get; set; }

    public System.DateTime Modified { get; set; }

    public bool Inactive_Flag { get; set; }

    public Nullable<decimal> PlantCost { get; set; }

    public Nullable<decimal> DeliveryCost { get; set; }

    public Nullable<decimal> MaterialCost { get; set; }

    public Nullable<decimal> SGACost { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public decimal LineOfBusinessID { get; set; }

    public decimal DivisionID { get; set; }

    public string Country { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
