
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Company
{

    public Company()
    {

        this.Users = new HashSet<User>();

    }


    public decimal CompanyID { get; set; }

    public string CompanyName { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string ST { get; set; }

    public string Zip { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public string ServiceUrl { get; set; }

    public byte[] QuoteImage { get; set; }

    public decimal SourceSystemID { get; set; }

    public string ChannelID { get; set; }

    public Nullable<decimal> InstanceID { get; set; }

    public string CompanyCode { get; set; }

    public Nullable<bool> UsesCategories { get; set; }

    public decimal MaxQuantity { get; set; }

    public Nullable<decimal> DefaultUomID { get; set; }

    public string Cert509 { get; set; }

    public bool UsesSAML { get; set; }

    public string TimeoutRedirect { get; set; }

    public bool ChangeProjectCode { get; set; }

    public bool UsesPriceIntegration { get; set; }

    public bool UsesSalesOrders { get; set; }

    public string Country { get; set; }

    public System.DateTime MsModificationDate { get; set; }



    public virtual ICollection<User> Users { get; set; }

}

}
