
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Competitor
{

    public decimal CompetitorID { get; set; }

    public decimal CompanyID { get; set; }

    public string CompetitorName { get; set; }

    public System.DateTime Inserted { get; set; }

    public System.DateTime Modified { get; set; }

    public bool Inactive { get; set; }

    public Nullable<decimal> UserID { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public string Country { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
