
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class CustomerEvent
{

    public decimal CustomerEventID { get; set; }

    public Nullable<bool> Private { get; set; }

    public Nullable<decimal> OwnerID { get; set; }

    public decimal EventTypeID { get; set; }

    public System.DateTime EventStartDate { get; set; }

    public Nullable<System.DateTime> EventEndDate { get; set; }

    public Nullable<System.DateTime> CompletedDate { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> ContactID { get; set; }

    public decimal UserID { get; set; }

    public decimal EventFrequencyID { get; set; }

    public Nullable<decimal> ProjectID { get; set; }

    public Nullable<decimal> MasterEventID { get; set; }

    public decimal EventStatusID { get; set; }

    public string Subject { get; set; }

    public Nullable<decimal> ProspectID { get; set; }

    public Nullable<System.DateTime> RecurrenceEndDate { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
