
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Division
{

    public decimal DivisionID { get; set; }

    public string DivisionName { get; set; }

    public decimal CompanyID { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string ST { get; set; }

    public string Zip { get; set; }

    public string Country { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
