
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class OrderDetail
{

    public decimal OrderDetailID { get; set; }

    public decimal OrderID { get; set; }

    public decimal ProductID { get; set; }

    public decimal Quantity { get; set; }

    public decimal UnitPrice { get; set; }

    public bool Mix { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
