
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Order
{

    public decimal OrderID { get; set; }

    public decimal CompanyID { get; set; }

    public Nullable<decimal> ProjectID { get; set; }

    public Nullable<decimal> year { get; set; }

    public Nullable<decimal> month { get; set; }

    public Nullable<decimal> YardsActual { get; set; }

    public Nullable<decimal> MaterialCost { get; set; }

    public Nullable<decimal> DollarsActual { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<System.DateTime> ShipDate { get; set; }

    public Nullable<decimal> YardsTicketed { get; set; }

    public Nullable<System.DateTime> OnJobTime { get; set; }

    public Nullable<decimal> LocationID { get; set; }

    public Nullable<decimal> ProspectID { get; set; }

    public Nullable<decimal> DispatchOrderID { get; set; }

    public string DispatchOrderNumber { get; set; }

    public string SalesmanCode { get; set; }

    public Nullable<System.DateTime> Inserted { get; set; }

    public Nullable<System.DateTime> Modified { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
