
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class PlantProductPrice
{

    public decimal PlantProductPriceID { get; set; }

    public decimal PlantID { get; set; }

    public decimal ProductID { get; set; }

    public decimal ListPrice { get; set; }

    public string Description { get; set; }

    public decimal PriceListID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public string PriceExtensionCode { get; set; }

}

}
