
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProductType
{

    public decimal ProductTypeID { get; set; }

    public decimal CompanyID { get; set; }

    public string ProductTypeName { get; set; }

    public string ProductTypeCode { get; set; }

    public decimal ProductLineID { get; set; }

    public decimal ListPrice { get; set; }

    public Nullable<decimal> UOMID { get; set; }

    public bool Inactive { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
