
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProductTemplate
{

    public decimal ProductTemplateID { get; set; }

    public string TemplateName { get; set; }

    public decimal CompanyUserID { get; set; }

    public bool Inactive { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public bool Shared { get; set; }

}

}
