
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Product
{

    public decimal ProductID { get; set; }

    public decimal CompanyID { get; set; }

    public string ProductName { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<decimal> AU_ID { get; set; }

    public Nullable<decimal> UnitOfMeasureID { get; set; }

    public decimal ProductTypeID { get; set; }

    public string ConnectionCode { get; set; }

    public string ITEM_CAT { get; set; }

    public string Product_Code { get; set; }

    public Nullable<System.DateTime> Inserted { get; set; }

    public Nullable<System.DateTime> Modified { get; set; }

    public string extProduct_Code { get; set; }

    public bool IsSellable { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public string ProductShortName { get; set; }

}

}
