
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProductLine
{

    public decimal ProductLineID { get; set; }

    public decimal CompanyID { get; set; }

    public string ProductLineCode { get; set; }

    public string ProductLineName { get; set; }

    public bool Active { get; set; }

    public string extProductLineCode { get; set; }

    public decimal LineOfBusinessID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
