
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectBidder
{

    public decimal ProjectBidderID { get; set; }

    public decimal ProjectID { get; set; }

    public decimal ProspectID { get; set; }

    public Nullable<bool> Quoted { get; set; }

    public Nullable<bool> StatusSub { get; set; }

    public Nullable<System.DateTime> QuoteDate { get; set; }

    public Nullable<bool> NotLIkeLIst { get; set; }

    public Nullable<decimal> StatusID { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public string ProjectCode { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public string PONumber { get; set; }

    public Nullable<decimal> MinLoadCharge { get; set; }

    public Nullable<decimal> SundryCharge { get; set; }

    public Nullable<decimal> SeasonalCharge { get; set; }

    public Nullable<decimal> UnloadCharge { get; set; }

    public string CustJobNbr { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public Nullable<System.DateTime> EffectiveDate { get; set; }

}

}
