
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectCharge
{

    public decimal ChargeID { get; set; }

    public string ChargeName { get; set; }

    public decimal ChargeType { get; set; }

    public string ChargeCode { get; set; }

    public decimal CompanyID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
