
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Project
{

    public decimal ProjectID { get; set; }

    public Nullable<bool> Private { get; set; }

    public Nullable<decimal> OwnerID { get; set; }

    public decimal CompanyID { get; set; }

    public string ProjectName { get; set; }

    public decimal ProjectTypeID { get; set; }

    public decimal StatusID { get; set; }

    public System.DateTime StatusChangeDate { get; set; }

    public decimal SourceID { get; set; }

    public bool Active { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string County { get; set; }

    public string State { get; set; }

    public string ZipCode { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public decimal SalespersonID { get; set; }

    public Nullable<System.DateTime> BidDate { get; set; }

    public Nullable<decimal> LostReasonID { get; set; }

    public Nullable<decimal> LostToID { get; set; }

    public string LostNote { get; set; }

    public System.DateTime Inserted { get; set; }

    public Nullable<System.DateTime> Modified { get; set; }

    public decimal PrevStatus { get; set; }

    public Nullable<bool> Exported { get; set; }

    public Nullable<decimal> WinningProjectBidderID { get; set; }

    public Nullable<System.DateTime> StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public Nullable<decimal> TotalYards { get; set; }

    public string ConnectionCode { get; set; }

    public string CustCode { get; set; }

    public string ProjectCode { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> GeofenceID { get; set; }

    public string Country { get; set; }

    public string ProjectDescription { get; set; }

    public Nullable<decimal> ZoneCodeID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
