
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectProduct
{

    public decimal ProjectProductID { get; set; }

    public decimal ProjectID { get; set; }

    public decimal Qty { get; set; }

    public Nullable<decimal> UOMID { get; set; }

    public System.DateTime Inserted { get; set; }

    public System.DateTime Modified { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> ProductLineID { get; set; }

    public Nullable<decimal> ProductTypeID { get; set; }

    public Nullable<decimal> ProductID { get; set; }

    public Nullable<decimal> PsiID { get; set; }

    public Nullable<decimal> ProductUsageID { get; set; }

    public string Note { get; set; }

    public Nullable<bool> Forecasted { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public Nullable<decimal> Freight { get; set; }

    public Nullable<decimal> FreightPay { get; set; }

    public Nullable<decimal> CompetitorPrice { get; set; }

    public string Category { get; set; }

    public string Description { get; set; }

    public Nullable<decimal> LineOfBusinessID { get; set; }

    public Nullable<decimal> StatusID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public Nullable<decimal> LostReasonID { get; set; }

    public Nullable<decimal> LostToID { get; set; }

    public string LostNote { get; set; }

    public string PriceExtensionCode { get; set; }

}

}
