
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ProjectType
{

    public decimal ProjectTypeID { get; set; }

    public decimal CompanyID { get; set; }

    public string ConnectionCode { get; set; }

    public string SANL_Code { get; set; }

    public string ProjectTypeName { get; set; }

    public string ShortName { get; set; }

    public System.DateTime Inserted { get; set; }

    public System.DateTime Modified { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
