
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Prospect
{

    public decimal ProspectID { get; set; }

    public Nullable<bool> Private { get; set; }

    public Nullable<decimal> OwnerID { get; set; }

    public decimal CompanyID { get; set; }

    public string ProspectName { get; set; }

    public System.DateTime Inserted { get; set; }

    public System.DateTime Modified { get; set; }

    public string ProspectCode { get; set; }

    public string ConnectionCode { get; set; }

    public string LocalCustNumber { get; set; }

    public string LocalCustName { get; set; }

    public bool IsCustomer { get; set; }

    public Nullable<decimal> Credit_Status_ID { get; set; }

    public string CustomerStatus { get; set; }

    public Nullable<decimal> Sales { get; set; }

    public Nullable<decimal> Margin { get; set; }

    public Nullable<decimal> MaterialMargin { get; set; }

    public Nullable<decimal> JobCount { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Zip { get; set; }

    public string Phone { get; set; }

    public Nullable<decimal> HighestBalance { get; set; }

    public Nullable<decimal> AvgInvoiceAmt { get; set; }

    public Nullable<decimal> AvgDaysToPay { get; set; }

    public Nullable<decimal> AvgDaysPastDue { get; set; }

    public Nullable<decimal> TotalDue { get; set; }

    public Nullable<decimal> ZeroTo30Days { get; set; }

    public Nullable<decimal> ThirtyOneTo60Days { get; set; }

    public Nullable<decimal> SixtyOneTo90Days { get; set; }

    public Nullable<decimal> NinetyOneTo120Days { get; set; }

    public Nullable<decimal> Over120Days { get; set; }

    public Nullable<decimal> CustomerTypeID { get; set; }

    public string StatementFrequency { get; set; }

    public Nullable<decimal> FinanceRate { get; set; }

    public Nullable<decimal> PaymentTermsID { get; set; }

    public string SalesmanCode { get; set; }

    public string Fax { get; set; }

    public string WebSite { get; set; }

    public Nullable<decimal> AvgRevenue { get; set; }

    public string NumberofEmployees { get; set; }

    public string CompanyOriginDate { get; set; }

    public Nullable<decimal> BusinessTypeID { get; set; }

    public string Notes { get; set; }

    public string Country { get; set; }

    public Nullable<bool> PORequired { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
