
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Quote
{

    public decimal QuoteID { get; set; }

    public decimal ProjectBidderID { get; set; }

    public Nullable<decimal> ContactID { get; set; }

    public Nullable<decimal> TermsID { get; set; }

    public string Attention { get; set; }

    public string Phone { get; set; }

    public string CellPhone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public System.DateTime QuoteDate { get; set; }

    public System.DateTime FirmUntilDate { get; set; }

    public decimal QuoteSequenceNumber { get; set; }

    public decimal QuoteTypeID { get; set; }

    public System.DateTime DateCreated { get; set; }

    public System.DateTime DateLastModified { get; set; }

    public string CustomerQuoteID { get; set; }

    public bool Exported { get; set; }

    public Nullable<System.DateTime> EscalationDate { get; set; }

    public string QuoteNote { get; set; }

    public string EscalationAmount { get; set; }

    public decimal QuoteStatusID { get; set; }

    public string Notes { get; set; }

    public Nullable<decimal> CreatedByID { get; set; }

    public Nullable<System.DateTime> OrderDate { get; set; }

    public Nullable<System.DateTime> StartOrderDate { get; set; }

    public Nullable<System.DateTime> ExpireOrderDate { get; set; }

    public Nullable<decimal> VehicleTypeID_1 { get; set; }

    public Nullable<decimal> VehicleTypeID_2 { get; set; }

    public Nullable<decimal> VehicleTypeID_3 { get; set; }

    public Nullable<decimal> VehicleTypeID_4 { get; set; }

    public Nullable<decimal> VehicleTypeID_5 { get; set; }

    public string CustomerOrderID { get; set; }

    public string PurchaseOrder { get; set; }

    public Nullable<System.DateTime> BeginDate { get; set; }

    public Nullable<bool> ApexNoteID { get; set; }

    public Nullable<bool> AllowBeforeStart { get; set; }

    public Nullable<bool> AllowAfterEnd { get; set; }

    public Nullable<bool> AllowExceedQty { get; set; }

    public Nullable<bool> AllowExceedLoads { get; set; }

    public Nullable<bool> AllowAfterComplete { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public Nullable<decimal> SalespersonID { get; set; }

}

}
