
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class QuoteSurcharge
{

    public decimal QuoteSurchargeID { get; set; }

    public decimal QuoteID { get; set; }

    public decimal SurchargeID { get; set; }

    public decimal Rate { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
