
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class QuoteType
{

    public decimal QuoteTypeID { get; set; }

    public decimal CompanyID { get; set; }

    public string QuoteTypeName { get; set; }

    public string Section1 { get; set; }

    public string Section2 { get; set; }

    public string Section3 { get; set; }

    public string ImageLocation { get; set; }

    public bool Inactive { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
