
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class QuoteSection
{

    public decimal QuoteSectionID { get; set; }

    public decimal QuoteTypeID { get; set; }

    public byte[] SectionContent { get; set; }

    public decimal PositionTop { get; set; }

    public decimal PositionLeft { get; set; }

    public decimal Height { get; set; }

    public decimal Width { get; set; }

    public bool IsProducts { get; set; }

    public bool IsSurcharges { get; set; }

    public bool IsLogo { get; set; }

    public bool IsCompanyInfo { get; set; }

    public bool IsCustomerInfo { get; set; }

    public bool IsSignature { get; set; }

    public bool IsExpiration { get; set; }

    public bool IsQuoteNumber { get; set; }

    public string ProductColumns { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
