
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class SalespersonContact
{

    public decimal SalesPersonContactID { get; set; }

    public decimal SalesPersonID { get; set; }

    public decimal ContactID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
