
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ScheduleDetail
{

    public decimal ScheduleID { get; set; }

    public decimal PourScheduleID { get; set; }

    public Nullable<decimal> year { get; set; }

    public Nullable<decimal> monthYds { get; set; }

    public Nullable<decimal> monthPercent { get; set; }

    public decimal Month { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
