
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ScheduleItem
{

    public decimal ScheduleItemID { get; set; }

    public decimal ScheduleID { get; set; }

    public decimal Quantity { get; set; }

    public System.DateTime Month { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
