
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class StandardClaus
{

    public decimal StandardClauseID { get; set; }

    public string Name { get; set; }

    public string StandardClauseText { get; set; }

    public Nullable<decimal> ProductLineID { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public Nullable<decimal> ProductID { get; set; }

    public bool Inactive { get; set; }

    public decimal CompanyID { get; set; }

    public Nullable<decimal> ProductUsageID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
