
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Surcharge
{

    public decimal SurchargeID { get; set; }

    public decimal CompanyID { get; set; }

    public string SurchargeName { get; set; }

    public decimal Rate { get; set; }

    public decimal UOMID { get; set; }

    public bool Active { get; set; }

    public bool QuoteDefault { get; set; }

    public bool QuoteSelectable { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public string LocalSurchargeID { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
