
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class TemplatedProduct
{

    public decimal TemplatedProductID { get; set; }

    public decimal ProductTemplateID { get; set; }

    public Nullable<decimal> ProductTypeID { get; set; }

    public Nullable<decimal> ProductID { get; set; }

    public Nullable<decimal> PlantID { get; set; }

    public Nullable<decimal> ProductUsageID { get; set; }

    public Nullable<decimal> LineOfBusinessID { get; set; }

    public Nullable<decimal> ProductLineID { get; set; }

    public Nullable<decimal> Qty { get; set; }

    public Nullable<decimal> Price { get; set; }

    public Nullable<decimal> Freight { get; set; }

    public Nullable<decimal> FreightPay { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IncludeInForecast { get; set; }

    public string Note { get; set; }

    public string Category { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public Nullable<decimal> UOMID { get; set; }

    public string PriceExtensionCode { get; set; }

}

}
