
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class TimeCalendar
{

    public decimal CalendarDateId { get; set; }

    public System.DateTime CalendarDate { get; set; }

    public Nullable<System.DateTime> DayEnd { get; set; }

    public System.DateTime FirstDayOfMonth { get; set; }

    public System.DateTime LastDayOfMonth { get; set; }

    public Nullable<System.DateTime> MonthEnd { get; set; }

    public System.DateTime FirstDayOfQtr { get; set; }

    public System.DateTime LastDayOfQtr { get; set; }

    public Nullable<System.DateTime> QuarterEnd { get; set; }

    public decimal Month { get; set; }

    public decimal Day { get; set; }

    public decimal Year { get; set; }

    public decimal DayOfWeek { get; set; }

    public decimal DayOfQtr { get; set; }

    public decimal DayOfYear { get; set; }

    public decimal WeekOfYear { get; set; }

    public decimal Quarter { get; set; }

    public string LastDayOfMonthFlag { get; set; }

    public string FirstDayOfQtrFlag { get; set; }

    public string LastDayOfQtrFlag { get; set; }

    public string MonthAbbrev { get; set; }

    public string DayAbbrev { get; set; }

    public string MonthName { get; set; }

    public string DayName { get; set; }

    public bool CompanyHoliday { get; set; }

    public bool BusinessDay { get; set; }

    public string MonthYearAbbrev { get; set; }

    public string QtrYearAbbrev { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
