
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class Unit_Of_Measure
{

    public decimal Unit_Of_Measure_ID { get; set; }

    public Nullable<decimal> CompanyID { get; set; }

    public string Imperial_Description { get; set; }

    public string Metric_Description { get; set; }

    public Nullable<decimal> Imperial_To_Metric_Conv_Factor { get; set; }

    public Nullable<decimal> Conversion_Factor_Type_ID { get; set; }

    public Nullable<decimal> Conversion_Factor_Value { get; set; }

    public string ConnectionCode { get; set; }

    public string UOM { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
