
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class User
{

    public decimal UserID { get; set; }

    public decimal CompanyID { get; set; }

    public string UserName { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public Nullable<bool> Active { get; set; }

    public Nullable<System.DateTime> InsertDate { get; set; }

    public string EmailAddress { get; set; }

    public byte[] Password { get; set; }

    public string CellPhoneNumber { get; set; }

    public string PhoneNumber { get; set; }

    public string FaxNumber { get; set; }

    public string SalesmanCode { get; set; }

    public Nullable<decimal> ReportsToID { get; set; }

    public decimal DeviationTypeID { get; set; }

    public Nullable<decimal> DeviationAmount { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string City { get; set; }

    public string ST { get; set; }

    public string Zip { get; set; }

    public Nullable<decimal> Latitude { get; set; }

    public Nullable<decimal> Longitude { get; set; }

    public bool UsesSAML { get; set; }

    public string Country { get; set; }

    public string DefaultMailMessage { get; set; }

    public System.DateTime MsModificationDate { get; set; }

    public Nullable<decimal> AdministratorID { get; set; }



    public virtual Company Company { get; set; }

}

}
