
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace mcTransmitter
{

using System;
    using System.Collections.Generic;
    
public partial class ValueAdd
{

    public decimal ValueAddID { get; set; }

    public Nullable<decimal> ProductLineID { get; set; }

    public Nullable<decimal> ProductTypeID { get; set; }

    public Nullable<decimal> ProductID { get; set; }

    public System.DateTime StartDate { get; set; }

    public Nullable<System.DateTime> EndDate { get; set; }

    public System.DateTime MsModificationDate { get; set; }

}

}
